---
# handlers file for post-install
# restart
- name: Restart service on CentOS
  service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == 'CentOS'
- name: Restart service on Ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_os_family == 'Ubuntu'
- name: Create a folder
  file:
    path: "{{ myDir }}"
    state: directory